# Introduccion a NumPy - Ejercicios

Empezamos a trabajar como data Analyst en una famosa panaderia de la ciudad, y el dueño require de nuestra ayuda para las recetas

### 1- Empieze importando NumPy como `np`

In [2]:
import numpy as np

Todas las recetas de la panaderia necesitan de `milk, eggs, sugar, flour, y butter`. Por ejemplo, un cupcake necesita de: `|Flour|Sugar|Eggs|Milk|Butter| 
|2 cups|0.75 cups|2 eggs|1 cups|0.5 cups|`
    
### 2- Cree un array de NumPy que represente esta data. Cada elemento debe ser un numero (por ejemplo `2` para "2 cups"). Guarde este array como `cupcakes`

In [4]:
cupcakes = np.array([ 2, 0.75, 2, 1, 0.5])
cupcakes

array([2.  , 0.75, 2.  , 1.  , 0.5 ])

El asistente de la panaderia ha compilado todas las recetas en un archivo `csv` llamado `recipes.csv`. Este archivo podrá encontrarlo en los links suministrados.

### 3- Cargue este archivo en una variable llamada `recipes`

In [6]:
recipes = np.genfromtxt('datasets/recipes.csv', dtype=None, delimiter=',')
recipes

array([(2.  , 0.75 , 2, 1, 0.5  ), (1.  , 0.125, 1, 1, 0.125),
       (2.75, 1.5  , 1, 0, 1.   ), (4.  , 0.5  , 2, 2, 0.5  )],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<i4'), ('f3', '<i4'), ('f4', '<f8')])

In [11]:
!pip3 install pandas

You should consider upgrading via the 'c:\users\natik\appdata\local\programs\python\python38-32\python.exe -m pip install --upgrade pip' command.


In [18]:
import pandas
recipes_2 = pandas.read_csv('datasets/recipes.csv').values
recipes_2

array([[1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

### 4- Imprima `recipes`

In [16]:
recipes

array([(2.  , 0.75 , 2, 1, 0.5  ), (1.  , 0.125, 1, 1, 0.125),
       (2.75, 1.5  , 1, 0, 1.   ), (4.  , 0.5  , 2, 2, 0.5  )],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<i4'), ('f3', '<i4'), ('f4', '<f8')])

Cada fila representa una receta diferente. Cada columna representa un ingrediente diferente:

`|Recipe|Cups of Flour|Cups of Sugar|Eggs|Cups of Milk|Cups of Butter|
 |Cupcakes|…|…|…|…|…| 
 |Pancake|…|…|…|…|…| 
 |Cookie|…|…|…|…|…| 
 |Bread|…|…|…|…|…|`

In [19]:
recipes_2

array([[1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

La tercera columna representa el numero de `eggs` que cada receta necesita. 

### 5- Seleccione todos los elementos de la tercera columna y guardelos en una variable llamada `eggs`

In [20]:
eggs = recipes_2[:,2]
eggs

array([1., 1., 2.])

### 6- Cuales recetas requiren exactamente 1 egg? Use una sentencia logica para obtener `True` o `False` para cada valor de `eggs`

In [21]:
eggs == 1

array([ True,  True, False])

El dueño quiere realizar dos tandas e cupcakes (primera fila) y una tanda de cookies (tercera fila)


### 7- Usted actualmente tiene una variable para `cupcakes`. Cree una variable para cookies con los datos de la tercera fila

In [24]:
cupcakes = recipes_2[0,:]
cupcakes

array([1.   , 0.125, 1.   , 1.   , 0.125])

In [25]:
cookies = recipes_2[2,:]
cookies

array([4. , 0.5, 2. , 2. , 0.5])

### 8- Obtenga el numero de ingredientes para dos tandas de cupcakes usando la multiplicacion en `cupcakes`. Guarde la nueva variable en  `double_batch`

In [27]:
double_batch = cupcakes * 2
double_batch

array([2.  , 0.25, 2.  , 2.  , 0.25])

### 9- Cree una nueva variable llamada `grocery_list` añadiendole `cookies` y `double_batch`

In [28]:
grocery_list = cookies + double_batch
grocery_list

array([6.  , 0.75, 4.  , 4.  , 0.75])