# Introducción a Numpy

## Arrays de Numpy

In [2]:
!pip3 install numpy

You should consider upgrading via the 'c:\users\natik\appdata\local\programs\python\python38-32\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np # alias

In [4]:
python_list = [1, 2, 3, 4, 5]
my_array = np.array(python_list)

In [5]:
my_array

array([1, 2, 3, 4, 5])

In [6]:
type(my_array)

numpy.ndarray

In [13]:
# sumar con for
l_plus_5 = []
for i in range(len(python_list)):
    l_plus_5.append(python_list[i] + 5)
l_plus_5

[6, 7, 8, 9, 10]

In [12]:
# sumar con list comprehension
l_plus_5 = [ i + 5 for i in python_list ]
l_plus_5

[6, 7, 8, 9, 10]

In [14]:
# sumar con numpy
np_array = np.array(python_list)
l_plus_5 = np_array + 5
l_plus_5

array([ 6,  7,  8,  9, 10])

In [15]:
np_array ** 2

array([ 1,  4,  9, 16, 25])

In [17]:
# Sumando arrays en numpy
np_array_1 = np.array([1, 2, 3, 4, 5, 6])
np_array_2 = np.array([7, 8, 9, 10, 11, 12])
np_array_1 + np_array_2

array([ 8, 10, 12, 14, 16, 18])

## Arrays de dos dimensiones

In [18]:
# Arrays separados
student1 = np.array([41, 24, 63, 76, 67])
student2 = np.array([42, 61, 63, 74, 12])
student3 = np.array([61, 85, 12, 76, 42])

In [19]:
## Arrays de dos dimensiones
all_students = np.array([
    student1,
    student2,
    student3
])
all_students

array([[41, 24, 63, 76, 67],
       [42, 61, 63, 74, 12],
       [61, 85, 12, 76, 42]])

In [23]:
two_dimension_array_1 = np.array([
    [1, 1],
    [2, 2],
    [3, 3],
    [4, 4],
    [5, 5]
])

two_dimension_array_2 = np.array([10, 10])
two_dimension_array_1 * two_dimension_array_2

array([[10, 10],
       [20, 20],
       [30, 30],
       [40, 40],
       [50, 50]])

## Seleccionando elementos de un array

In [25]:
two_dimension_array_1[0]

array([1, 1])

In [26]:
two_dimension_array_1[1:3]

array([[2, 2],
       [3, 3]])

In [27]:
two_dimension_array_1[:3]

array([[1, 1],
       [2, 2],
       [3, 3]])

In [30]:
# Se me olvida que el tercer parámetro es los saltos, en el caso de abajo es de 2 en 2
two_dimension_array_1[1:5:2]

array([[2, 2],
       [4, 4]])

## Seleccionar elementos de un array de 2 dimensiones

In [31]:
# Un solo elemento
# array[fila, columna]
two_dimension_array_1[0, 0]

1

In [46]:
# Para seleccionar múltiples elementos con slice
# array[fila_start:fila_end - 1, columan_start:columna_end - 1] (esto trae un análisis conceptual chistoso)
# Sin el menos uno a diferencia del slice de python
two_dimension_array_1[0:4, 0]

array([1, 2, 3, 4])

In [49]:
# Ejercicio
# https://files.slack.com/files-pri/T01BC9RCC94-F01DGRCPVRN/screenshot_from_2020-10-16_20-07-44.png
test1 = [92, 94, 88, 91, 87]
test2 = [79, 100, 86, 93, 91]
test3 = [87, 85, 72, 90, 92]
student_tests = np.array([
    test1,
    test2,
    test3
])
tanya_test_3 = student_tests[2, 0]
print("Tanya 3: ", tanya_test_3)
cody_test_scores = student_tests[:, 4]
print("Cody tests: ", cody_test_scores)

Tanya 3:  87
Cody tests:  [87 91 92]


In [51]:
# Más operaciones en arrays de 2 dimensiones
logic_array = np.array([10, 20, 4, 2, 1, 15, 30])
logic_array > 5

array([ True,  True, False, False, False,  True,  True])

In [53]:
logic_array[logic_array > 5]

array([10, 20, 15, 30])

In [54]:
logic_array[(logic_array > 5) | (logic_array < 2)]

array([10, 20,  1, 15, 30])

In [70]:
# Traer CSV a mano con numpy
csv_array = np.genfromtxt('datasets/sample.csv', dtype=None, delimiter=',')
csv_array

/Users/alejandroescobar/Projects/python/makeitreal/data-science/jupyter_numpy/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([(b'speakers', 2016, b'in stock'),
       (b'microphone', 2012, b'in stock'),
       (b'charger', 2018, b'out of stock')],
      dtype=[('f0', 'S10'), ('f1', '<i8'), ('f2', 'S12')])

In [62]:
!pip3 install pandas

     |████████████████████████████████| 9.9 MB 11.0 MB/s eta 0:00:01
     |████████████████████████████████| 510 kB 6.2 MB/s eta 0:00:01


In [71]:
# Traer CSV con pandas
import pandas
data = pandas.read_csv('datasets/sample.csv').values
data

array([['microphone', 2012, 'in stock'],
       ['charger', 2018, 'out of stock']], dtype=object)