In [1]:
# Introduccion a estadistica con Numpy

##Mean - media - promedio

In [4]:
import numpy as np
respuesta_encuesta = [1, 4, 5, 4.5, 3, 1, 5, 4.5]

In [5]:
respuesta_encuesta_arr = np.array(respuesta_encuesta)

In [6]:
np.mean(respuesta_encuesta_arr)

3.5

In [8]:
np.round(respuesta_encuesta, 2)

array([1. , 4. , 5. , 4.5, 3. , 1. , 5. , 4.5])

In [9]:
# np.mean(arr_tem[arr_tem >20])
# np.mean(arr_tem>20)
temperaturas = [17, 18, 20, 22, 18, 20, 27, 22, 25]
arr_tem = np.array(temperaturas)
arr_tem

array([17, 18, 20, 22, 18, 20, 27, 22, 25])

In [11]:
np.mean(arr_tem[arr_tem >20])

24.0

In [10]:
# Porcentaje de valores que cumple una condición
np.mean(arr_tem>20)

0.4444444444444444

In [13]:
## Media de arrays 2-d
tiros_al_aro = np.array([
    [10, 5, 0, 1],
    [7, 2, 3, 4],
    [8, 10, 1, 3]
])

In [14]:
#np.mean(tiros_al_aro)

0.4166666666666667

In [16]:
np.mean(tiros_al_aro > 0)

0.4166666666666667

In [17]:
np.mean(tiros_al_aro, axis=1)

array([0.5 , 0.25, 0.5 ])

In [18]:
np.mean(tiros_al_aro, axis=0)

array([0.66666667, 0.        , 0.66666667, 0.33333333])

In [33]:
### Valores atipicos (Outliers)
temperaturas = [2, 17, 18, 20, 22, 18, 20, 27, 22, 35]
temp_array = np.array(temperaturas)

In [28]:
array_sort = np.sort(temp_array)
array_sort

array([ 2, 17, 18, 18, 20, 20, 22, 22, 27, 35])

In [29]:
np.median(array_sort)

20.0

In [31]:
## mediana = 50th percentile
###EDA - Exploratory Data Analysis
## Explorar el dataset

In [35]:
# five number summary
# 25th - primer cuartil
# 50th - la mediana
# 75th tercer cuartil
# maximo

# rango intercuartil = dif(tercer cuartil - primer cuartil)
# value = el 50% de datos esta en esta valor
# np.percentile(array, value (25))
# medida de desviacion
# es una longitud
np.percentile(temp_array, 25)

18.0