In [1]:
import numpy as np

In [3]:
python_list = [2,3,4,5,1,2]
np_array=np.array(python_list)

In [4]:
np_array

array([2, 3, 4, 5, 1, 2])

In [5]:
type(np_array)

numpy.ndarray

In [6]:
l_plus_2=[]
for i in range(len(python_list)):
    l_plus_2.append(python_list[i]+2)
l_plus_2

[4, 5, 6, 7, 3, 4]

In [7]:
l_plus_2 = [elem + 2 for elem in python_list]
l_plus_2

[4, 5, 6, 7, 3, 4]

In [8]:
l_plus_2 = np_array + 2
l_plus_2

array([4, 5, 6, 7, 3, 4])

In [10]:
np_array**2

array([ 4,  9, 16, 25,  1,  4], dtype=int32)

In [11]:
np_array1 = np.array([1,2,1,2,3,4])
np_array2 = np.array([5,4,3,2,1,0])
np_array1 + np_array2

array([6, 6, 4, 4, 4, 4])

In [16]:
np_matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np_matrix_1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
np_matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np_matrix_2 = np.array([2,1,0])
np_matrix_1 * np_matrix_2

array([[ 2,  2,  0],
       [ 8,  5,  0],
       [14,  8,  0],
       [20, 11,  0]])

In [19]:
np_matrix_3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np_matrix_4 = np.array([[2],[1],[0]])
np_matrix_3 * np_matrix_4

ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 