In [4]:
import numpy as np
# Trabajamos para Netflix y queremos saber cuántas películas vieron los usuarios en una semana. 
# tenemos la siguiente data de 15 usuarios en un array.
movies_watched = np.array([2, 3, 8, 0, 2, 4, 3, 1, 1, 0, 5, 1, 1, 7, 2])
movies_watched

array([2, 3, 8, 0, 2, 4, 3, 1, 1, 0, 5, 1, 1, 7, 2])

In [24]:
# Encuentre el 25th y el 75th percentile, y guardelo en sus respectivas variables: first_quarter y third_quarter. 
first_quarter = np.percentile(np.sort(movies_watched), 25)
first_quarter

1.0

In [25]:
third_quarter = np.percentile(np.sort(movies_watched), 75)
third_quarter

3.5

In [8]:
# Cree una variable llamada interquartile_range. Calcule el rango intercuartil y guardelo allí. Imprima
interquartile_range = third_quarter - first_quarter
interquartile_range

2.5

In [15]:
# 2nd Part
clients = np.array([ 2, 6, 14, 4, 3, 9, 1, 11, 4, 2, 8])
clients

array([ 2,  6, 14,  4,  3,  9,  1, 11,  4,  2,  8])

In [17]:
np.sort(clients)

array([ 1,  2,  2,  3,  4,  4,  6,  8,  9, 11, 14])

In [21]:
time_wasted_30 = np.percentile(clients, 30)
time_wasted_30
# 30 % de los datos estan debajo de ese valor
# 70 % de los datos estan arriba de ese valor

3.0

In [22]:
time_wasted_70 = np.percentile(clients, 70)
time_wasted_70
# 70 % de los datos estan debajo de ese valor
# 30 % de los datos estan arriba de ese valor

8.0